### ISSUE TITLE
Spike: Check if Istio Ingress Gateway loadbalancer can be made internal.

### ISSUE THREAD

**Issue by bimalgrewal** [tranquilitybase-io/tb-gcp#118]

**Comment by bimalgrewal** [comment]
**Findings**

Istio Ingress gateway is only accessible through an external load balancer or a Node Port. It's advised that Node Port should not be be used in production to expose services.

1. [https://oteemo.com/2017/12/12/think-nodeport-kubernetes/](url)
2. [https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0](url)

@rjmco @gobindgft @parmendra17 Do you have views on this?

**Comment by bimalgrewal** [comment]
In the cluster creation step, If we install istio manually using helm and enable ILB then it should be possible. 

[https://cloud.google.com/solutions/using-istio-for-internal-load-balancing-of-grpc-services#create_a_gke_cluster_with_istio](enable ILB)

**Comment by connor-mcshane** [comment]
Just had a look with Stuart, setting up the cluster as private doesn't supersede this 

![image](https://user-images.githubusercontent.com/10451364/80585498-585d3c00-8a0b-11ea-94b5-172e4f9f6ffe.png)

Soo this still does need to get picked up

**Comment by willsc** [comment]
## Installing Istio on a private GKE cluster
- Run the following script to install Istio
  istio-install-script.sh
```
Checking kubectl is installed...
Checking curl is installed...
Downloading and installing Istio...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107  100   107    0     0    180      0 --:--:-- --:--:-- --:--:--   180
100  3896  100  3896    0     0   5293      0 --:--:-- --:--:-- --:--:--  5293
```

- Add the Istio firewall rule via the following script.
add_gcp_fw.sh ${clustername}

- Verify the istio service have been started.
```
kubectl  get pods -n istio-system
NAME                                            READY   STATUS    RESTARTS   AGE
grafana-74dc798895-j8mlb                        1/1     Running   0          2d
istio-egressgateway-7c6c6cd8b9-c9dpz            1/1     Running   0          2d
istio-ingressgateway-5d869f5bbf-9xnhg           1/1     Running   0          2d
istio-private-ingressgateway-7977887b9f-j9dkr   1/1     Running   0          23h
istio-tracing-8584b4d7f9-995bb                  1/1     Running   0          2d
istiod-648555b9b7-6hzgn                         1/1     Running   0          2d
kiali-6f457f5964-dl25g                          1/1     Running   0          2d
prometheus-7fb8c98b68-vxgqr                     2/2     Running   0          2d
```

- Setup the new private ingress gateway
```
kubectl apply -f istio-pvt-ingressgateway-deployment.yaml
kubectl apply -f istio-pvt-ingressgateway.yaml
```

- Verify that the internal gateway has been created.
```
kubectl get svc -n istio-system
NAME                           TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)                                                                      AGE
grafana                        ClusterIP      10.4.14.170   <none>         3000/TCP                                                                     2d
istio-egressgateway            ClusterIP      10.4.6.205    <none>         80/TCP,443/TCP,15443/TCP                                                     2d
istio-ingressgateway           LoadBalancer   10.4.13.61    34.89.81.218   15020:31110/TCP,80:32442/TCP,443:31768/TCP,31400:32731/TCP,15443:30828/TCP   2d
istio-private-ingressgateway   LoadBalancer   10.4.12.187   10.3.0.8       15020:32082/TCP,80:32366/TCP,443:30791/TCP,31400:31115/TCP,15443:31879/TCP   24h
istiod                         ClusterIP      10.4.10.188   <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP,53/UDP,853/TCP                         2d
jaeger-agent                   ClusterIP      None          <none>         5775/UDP,6831/UDP,6832/UDP                                                   2d
jaeger-collector               ClusterIP      10.4.3.44     <none>         14267/TCP,14268/TCP,14250/TCP                                                2d
jaeger-collector-headless      ClusterIP      None          <none>         14250/TCP                                                                    2d
jaeger-query                   ClusterIP      10.4.15.97    <none>         16686/TCP                                                                    2d
kiali                          ClusterIP      10.4.2.90     <none>         20001/TCP                                                                    2d
prometheus                     ClusterIP      10.4.5.57     <none>         9090/TCP                                                                     2d
tracing                        ClusterIP      10.4.7.1      <none>         80/TCP                                                                       2d
zipkin                         ClusterIP      10.4.12.151   <none>         9411/TCP                                                                     2d
```

- Deploying an application by first creating a gateway manifest.
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: private-ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```
- The selector matches  istio: private-ingressgateway which defined in the service manifest we defined to private ingress service manifest.
- Apply the gateway manifest .
```
kubectl apply -f app-gateway.yaml
```
- Apply the manifests for service, deployment, and virtualservice.
```
kubectl apply -f service.yaml

apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
```

```
kubectl apply -f deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: gcr.io/gcp-jenkins-project/helloworld-v1:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```

```
kubectl apply -f virtualservice.yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000

```
- Verify that pods are running.
```
NAME                            READY   STATUS    RESTARTS   AGE
helloworld-v1-6b548695c-cnvls   2/2     Running   0          23h

```
