### ISSUE TITLE
Define and create a Jenkinsfile to deploy an activator and also initiate a Jenkins worker(s)

### ISSUE THREAD

**Issue by willsc** [tranquilitybase-io/tb-gcp#345]
## Purpose
Why is this important?
Best practice dictates we run jobs on a slave rather than the Jenkins master.

## Relevant Info
Links to resources, documentation etc.

## Estimated Work to Complete
Steps to complete the task
1. Define the Jenkins steps required. Then put a small POC together for the Jenkins file.

## Definition of Done
 This is complete when:
- The Jenkinsfile is able to spin up a worker.
- When the Jenkinsfile is able to checkout the code from the repo and build and deploy the activiator.

**Comment by arvindclement** [comment]
@wills-gft I have the jenkins file ready once the issue with the Jenkins slaves are sorted out we can sync up and test the Jenkins file

**Comment by willsc** [comment]
Discovered that the Jenkins master had an issue with the permissions on docker.sock, I believe this should now be fixed with the following  Jenkins master Manifest.

```apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-master
  name: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-master
    spec:
      imagePullSecrets:
        - name: "docker-hub"
      spec:
      containers:
       - name: jenkins-master
         image: willsgft/jenkins-master:latest
         securityContext:
            privileged: true
            runAsUser: 0
         imagePullPolicy: "Always"
         volumeMounts:
          - mountPath: /var
            name: jenkins-home
            subPath: jenkins_home
          - name: docker-sock-volume
            mountPath: /var/run/docker.sock
         resources:
           requests:
             memory: "1024Mi"
             cpu: "0.5"
           limits: 
             memory: "1024Mi"
             cpu: "0.5"
         ports:
           - name: http-port
             containerPort: 8080
           - name: jnlp-port
             containerPort: 50000
      volumes:
       - name: jenkins-home
         persistentVolumeClaim:
          claimName: jenkins-master-pv-claim
       - name: docker-sock-volume
         hostPath:
           path: /var/run/docker.sock
           type: File
status: {}
```
The use of a new security context and runAs should fix this, I will retest this and confirm.
```
securityContext:
            privileged: true
            runAsUser: 0

```

**Comment by willsc** [comment]
The latest documentation of for the work done is here 
https://confluence.gft.com/display/MODAPPS/Issue%23345+-+Define+and+create+a+Jenkinsfile+to+deploy+an+activator+and+also+initiate+a+Jenkins+worker%28s%29-+wills-gft-+status+open

**Comment by wills-gft** [comment]
Changes for the jenkins-master manifest to support credentials.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-master
  name: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-master
    spec:
      imagePullSecrets:
        - name: "docker-hub"
      spec:
      containers:
       - name: jenkins-master
         image: gcr.io/tranquility-base-images/tb-jenkins_latest:landingzone
         securityContext:
            privileged: true
            runAsUser: 0
         imagePullPolicy: "Always"
         volumeMounts:
          - mountPath: /var
            name: jenkins-home
            subPath: jenkins_home
          - name: docker-sock-volume
            mountPath: /var/run/docker.sock
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/ec-service-account-config.json
         resources:
           requests:
             memory: "1024Mi"
             cpu: "0.5"
           limits: 
             memory: "1024Mi"
             cpu: "0.5"
         ports:
           - name: http-port
             containerPort: 8080
           - name: jnlp-port
             containerPort: 50000
      volumes:
       - name: config-volume
          configMap:
            name: ec-config            
       - name: google-cloud-key
          secret:
            secretName: ec-service-account
       - name: jenkins-home
         persistentVolumeClaim:
          claimName: jenkins-master-pv-claim
       - name: docker-sock-volume
         hostPath:
           path: /var/run/docker.sock
           type: File
status: {}
```
