### ISSUE TITLE
Cloud DNS Terraform module

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#52]
create a Cloud DNS Terraform module that enabled FQDN addressing of TB resources.

Not sure whether to deploy directly into the Shared VPC host project or into service project attached to host project. Need to investigate this.

Create private zone for each project using the org node domain. e.g. telemetry.tranquilitybase.io for the telemetry project in the tranquilitybase.io org.

For instance the iTop gui could be accessible by using itop.srvicemanagement.tranquilitybase.io

***
DOD: To be able to connect to the eagle console from a specific domain.

**Comment by andy12838729** [comment]
Can we use the CFT for this ?

**Comment by connor-mcshane** [comment]
From skim reading I am thinking this refers to  cloud dns private zone, which would be used as a DNS for any of the VPCs.

At this point, I think we need to create the DNS private zone in the HOST project (shared networking), then add any of the compute or Kubernetes servers to the DNS which should give us a lookup.

What I will do is try and configure a private DNS manually on an existing Tbase deployment, make sure that works and then look to integrate the creation of the DNS in the terraform scripts.

https://cloud.google.com/vpc/docs/shared-vpc#shared_vpc_and_cloud_dns_private_zones
https://www.jhanley.com/google-cloud-private-dns-zones/
https://www.terraform.io/docs/providers/google/d/dns_managed_zone.html

**Comment by Salles-FA** [comment]
- The UI is currently fetching the API at globalThis.location.origin
- There's a configuration to reverse DNS the API (Houston Service) at "/api"
- And the APIs (Houston and DaC) are using kubernetes POD internal hostnames

See [eagle_console.yaml](https://github.com/tranquilitybase-io/tb-gcp/blob/master/tb-gcp-tr/landingZone/eagle_console.yaml)

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: houstonservice
spec:
  hosts:
    - "*"
  gateways:
    - mygateway
  http:
    - match:
        - uri:
            prefix: /api   <---------------------------------
      route:
        - destination:
            host: houstonservice
            port:
              number: 80
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - PATCH
          - DELETE
        allowHeaders:
          - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eagleconsole
spec:
  hosts:
    - "*"
  gateways:
    - mygateway
  http:
    - route:
        - destination:
            host: eagleconsole
            port:
              number: 80
```
